# -*- coding: utf-8 -*-
"""Intro to Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QRO8p3xH7qPfFUBFBAuh-mnhg5jioyY4
"""

2+2

import torch

!pip list