# -*- coding: utf-8 -*-
"""Tensors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJUMJRn5ZwcgPeynvdc7HzOwRHGX3sZz

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.
"""

import torch
import numpy as np

"""# **LISTS**

"""

my_list = [1, 2, 3, 4, 5]
my_list

my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

"""# **NUMPY ARRAYS**

"""

np1 = np.random.rand(3, 4)
np1

np1.dtype

"""# **TENSORS**

"""

tensor_2d1 = torch.randn(3, 4)
tensor_2d1

tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

